import jsPDF from "jspdf";
import type { BlueprintData } from "@/data/mockReport";

export function generateBlueprintPdf(blueprint: BlueprintData, idea: string) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > 270) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Gold Rush — Startup Blueprint", margin, y);
  y += 10;
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text(idea, margin, y);
  y += 12;

  const sections: { title: string; content: string | string[] }[] = [
    { title: "Product Concept", content: blueprint.productConcept },
    { title: "Strategic Positioning", content: blueprint.strategicPositioning },
    { title: "Core Features", content: blueprint.coreFeatures },
    { title: "Target Users", content: blueprint.targetUsers },
    { title: "Monetization Strategy", content: blueprint.monetization },
    { title: "MVP Plan", content: blueprint.mvpPlan },
  ];

  sections.forEach(({ title, content }) => {
    checkPage(20);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    if (typeof content === "string") {
      const lines = doc.splitTextToSize(content, contentWidth);
      checkPage(lines.length * 5);
      doc.text(lines, margin, y);
      y += lines.length * 5 + 6;
    } else {
      content.forEach((item, i) => {
        checkPage(8);
        const lines = doc.splitTextToSize(`${i + 1}. ${item}`, contentWidth - 4);
        doc.text(lines, margin + 2, y);
        y += lines.length * 5 + 2;
      });
      y += 4;
    }
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by Gold Rush • goldrush.ai", margin, 285);

  doc.save(`GoldRush_Blueprint_${idea.replace(/\s+/g, "_").slice(0, 30)}.pdf`);
}
