import jsPDF from "jspdf";
import type { BlueprintData } from "@/data/mockReport";

export function generateBlueprintPdf(blueprint: BlueprintData, idea: string) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const bottomMargin = 20;
  const maxY = pageHeight - bottomMargin;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > maxY) {
      doc.addPage();
      y = 20;
    }
  };

  /** Write wrapped text line-by-line with page breaks */
  const writeLines = (lines: string[], x: number, lineHeight: number) => {
    for (const line of lines) {
      checkPage(lineHeight);
      doc.text(line, x, y);
      y += lineHeight;
    }
  };

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Gold Rush — Startup Blueprint", margin, y);
  y += 10;
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  const ideaLines = doc.splitTextToSize(idea, contentWidth);
  writeLines(ideaLines, margin, 6);
  y += 6;

  const sections: { title: string; content: string | string[] }[] = [
    { title: "Product Concept", content: blueprint.productConcept },
    { title: "Strategic Positioning", content: blueprint.strategicPositioning },
    { title: "Core Features", content: blueprint.coreFeatures },
    { title: "Target Users", content: blueprint.targetUsers },
    { title: "Monetization Strategy", content: blueprint.monetization },
    { title: "MVP Plan", content: blueprint.mvpPlan },
  ];

  sections.forEach(({ title, content }) => {
    checkPage(14);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    if (typeof content === "string") {
      const lines = doc.splitTextToSize(content, contentWidth);
      writeLines(lines, margin, 5);
      y += 6;
    } else {
      content.forEach((item, i) => {
        const lines = doc.splitTextToSize(`${i + 1}. ${item}`, contentWidth - 4);
        writeLines(lines, margin + 2, 5);
        y += 2;
      });
      y += 4;
    }
  });

  // Footer on every page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text("Generated by Gold Rush • goldrush.ai", margin, pageHeight - 10);
  }

  doc.save(`GoldRush_Blueprint_${idea.replace(/\s+/g, "_").slice(0, 30)}.pdf`);
}
