import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { useNavigate, useParams } from "react-router-dom";
import { Download, ArrowRight, Bookmark, BookmarkCheck, Eye, Loader2, Trophy, Brain, Search, Microscope, Crosshair, Map, GitCompare, MessageSquare, Target, DollarSign, BarChart3, Wrench, Compass } from "lucide-react";
import { generateReportPdf } from "@/lib/generateReportPdf";
import { SignalCard } from "@/components/report/SignalCard";
import { OpportunitySection } from "@/components/report/OpportunitySection";
import { RevenueBenchmark } from "@/components/report/RevenueBenchmark";
import { NicheAnalysis } from "@/components/report/NicheAnalysis";
import { UnitEconomics } from "@/components/report/UnitEconomics";
import { BuildComplexity } from "@/components/report/BuildComplexity";
import { BlueprintSection } from "@/components/report/BlueprintSection";
import { OpenSourceLandscape } from "@/components/report/OpenSourceLandscape";
import { ScoreRing } from "@/components/report/ScoreRing";
import { KeyStatsBar } from "@/components/report/KeyStatsBar";
import { UserQuotesSection } from "@/components/report/UserQuotesSection";
import { MethodologySection } from "@/components/report/MethodologySection";
import { GlossarySection } from "@/components/report/GlossarySection";
import { ProofDashboard } from "@/components/report/ProofDashboard";
import { KeywordDemand } from "@/components/report/KeywordDemand";
import { AppStoreIntelligence } from "@/components/report/AppStoreIntelligence";
import { RecommendedStrategy } from "@/components/report/RecommendedStrategy";
import { MarketExploitMap } from "@/components/report/MarketExploitMap";
import { CompetitorMatrix } from "@/components/report/CompetitorMatrix";
import { FounderDecision } from "@/components/report/FounderDecision";
import { KillShotAnalysis } from "@/components/report/KillShotAnalysis";
import { ReviewIntelligence } from "@/components/report/ReviewIntelligence";
import { EvidenceStrength } from "@/components/report/EvidenceStrength";
import { FounderInsight } from "@/components/report/FounderInsight";
import { ThemeToggle } from "@/components/ThemeToggle";
import { NotificationBell } from "@/components/NotificationBell";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import type { MockReportData } from "@/data/mockReport";
import { mockReport } from "@/data/mockReport";
import { toast } from "sonner";
import { ReportNavigator } from "@/components/report/ReportNavigator";
import { ReportLayerHeader } from "@/components/report/ReportLayerHeader";
import { DataQualityGroup } from "@/components/report/DataQualityGroup";
import { ScoreDeepDive } from "@/components/report/ScoreDeepDive";
import { CollapsibleSection } from "@/components/report/CollapsibleSection";

/** Section subtitles for card titles */
const sectionSubtitles: Record<string, string> = {
  "Trend Momentum": "Is interest growing or fading?",
  "Market Saturation": "How crowded is this market?",
  "Competitor Snapshot": "Who are you up against?",
  "Sentiment & Pain Points": "What real users love and hate",
  "Growth Signals": "Signs this market is heating up",
};

import { safeValue } from "@/lib/safeValue";

const Report = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const { user, loading } = useAuth();
  const [report, setReport] = useState<MockReportData | null>(null);
  const [loadingReport, setLoadingReport] = useState(true);
  const [isTracked, setIsTracked] = useState(false);
  const [trackingLoading, setTrackingLoading] = useState(false);
  const [pdfGenerating, setPdfGenerating] = useState(false);

  useEffect(() => {
    if (!loading && !user) navigate("/auth", { replace: true });
  }, [user, loading, navigate]);

  useEffect(() => {
    if (!id || !user) return;

    let cancelled = false;

    const loadReport = async () => {
      setLoadingReport(true);
      try {
        const { data, error } = await supabase
          .from("analyses")
          .select("*")
          .eq("id", id)
          .single();

        if (cancelled) return;

        if (error || !data) {
          toast.error("Report not found.");
          navigate("/dashboard", { replace: true });
          return;
        }

        if (data.report_data) {
          const rd = data.report_data as unknown as MockReportData;
          // Only use blueprint_data (explicitly generated by user) — never auto-use the pipeline-generated blueprint from report_data
          const savedBlueprint = data.blueprint_data as unknown as MockReportData["blueprint"] | null;
          setReport({
            ...rd,
            overallScore: data.overall_score ?? rd.overallScore,
            signalStrength: (data.signal_strength as MockReportData["signalStrength"]) ?? rd.signalStrength,
            blueprint: savedBlueprint || {
              productConcept: "",
              strategicPositioning: "",
              coreFeatures: [],
              targetUsers: [],
              monetization: [],
              mvpPlan: [],
            },
          });
          return;
        }

        if (data.status === "failed") {
          const reportError = (data.report_data as any)?.error;
          const reportMessage = (data.report_data as any)?.message;
          toast.error(
            reportError === "insufficient_data"
              ? reportMessage || "Insufficient data to analyze this idea."
              : reportMessage || "Analysis failed. Please try again.",
          );
          navigate("/dashboard", { replace: true });
          return;
        }

        if (data.status === "complete") {
          toast.error("This report couldn't be generated. Please retry the analysis.");
          navigate("/dashboard", { replace: true });
          return;
        }

        navigate(`/processing/${id}`, { replace: true });
      } catch {
        if (!cancelled) {
          toast.error("Failed to load report.");
          navigate("/dashboard", { replace: true });
        }
      } finally {
        if (!cancelled) setLoadingReport(false);
      }
    };

    loadReport();

    // Check if already tracked
    supabase
      .from("watchlist")
      .select("id")
      .eq("user_id", user.id)
      .eq("analysis_id", id)
      .maybeSingle()
      .then(({ data }) => {
        if (data && !cancelled) setIsTracked(true);
      });

    return () => {
      cancelled = true;
    };
  }, [id, user, navigate]);

  const handleTrack = async () => {
    if (!user || !id || !report) return;
    setTrackingLoading(true);

    try {
      if (isTracked) {
        await supabase.from("watchlist").delete().eq("user_id", user.id).eq("analysis_id", id);
        setIsTracked(false);
        toast.success("Removed from watchlist");
      } else {
        const { error } = await supabase.from("watchlist").insert({
          user_id: user.id,
          analysis_id: id,
          idea: report.idea,
          current_score: report.overallScore,
          last_analyzed_at: new Date().toISOString(),
        });
        if (error) {
          toast.error("Something went wrong — please try again");
        } else {
          setIsTracked(true);
          toast.success("Added to watchlist! Track it from your Idea Watchlist.");
        }
      }
    } finally {
      setTrackingLoading(false);
    }
  };

  if (loadingReport) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <p className="text-muted-foreground">Loading report…</p>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center px-6">
        <div className="text-center">
          <p className="text-foreground font-medium">This report is unavailable.</p>
          <Button className="mt-4" onClick={() => navigate("/dashboard")}>Back to dashboard</Button>
        </div>
      </div>
    );
  }

  const r = report;
  const totalEvidence = r.signalCards.reduce((sum, c) => sum + (c.evidenceCount || 0), 0);

  return (
    <div className="min-h-screen bg-background">
      <ReportNavigator />

      <nav className="flex items-center justify-between px-4 sm:px-6 py-4 max-w-6xl mx-auto border-b border-border/50">
        <span className="font-heading text-xl font-bold text-foreground shrink-0">⛏️ Gold Rush</span>
        <div className="flex items-center gap-1 sm:gap-2">
          <NotificationBell />
          <ThemeToggle />
          <Button variant="outline" size="sm" onClick={() => navigate("/watchlist")} className="hidden sm:inline-flex">
            <Eye className="w-3.5 h-3.5 mr-1" /> Watchlist
          </Button>
          <Button variant="outline" size="icon" className="sm:hidden w-8 h-8" onClick={() => navigate("/watchlist")}>
            <Eye className="w-3.5 h-3.5" />
          </Button>
          <Button variant="outline" size="sm" onClick={() => navigate("/dashboard")} className="hidden sm:inline-flex">
            Dashboard
          </Button>
          <Button variant="outline" size="icon" className="sm:hidden w-8 h-8" onClick={() => navigate("/dashboard")}>
            <ArrowRight className="w-3.5 h-3.5" />
          </Button>
        </div>
      </nav>

      <main id="report-content" className="max-w-6xl mx-auto px-6 py-10 lg:pr-24">

        {/* ═══════════════════════════════════════════════════════
            LAYER 1 — VERDICT
            ═══════════════════════════════════════════════════════ */}
        <ReportLayerHeader
          id="layer-verdict"
          title="Verdict"
          subtitle="Your idea at a glance"
          icon={<Trophy className="w-4 h-4 text-primary" />}
          className="pt-0"
        />

        {/* Idea + Score */}
        <div className="mb-8 mt-4">
          <div className="flex items-start justify-between gap-4 mb-6">
            <h1 className="font-heading text-2xl md:text-3xl font-bold text-foreground">{r.idea}</h1>
            <Button
              variant={isTracked ? "default" : "outline"}
              size="sm"
              onClick={handleTrack}
              disabled={trackingLoading}
              className="shrink-0"
            >
              {isTracked ? (
                <><BookmarkCheck className="w-4 h-4 mr-1" /> Tracking</>
              ) : (
                <><Bookmark className="w-4 h-4 mr-1" /> Track This Idea</>
              )}
            </Button>
          </div>
          <ScoreRing score={r.overallScore} signalStrength={r.signalStrength} />
          <p className="text-sm text-muted-foreground mt-4">
            Analysis based on <span className="font-semibold text-foreground">{r.dataSources?.length || totalEvidence}</span> verified data points from {r.dataSources?.length ? `${r.dataSources.length} sources` : "Reddit, App Store, and Google Trends"}.
          </p>
          {r.dataSources && r.dataSources.length > 0 && (
            <details className="mt-2">
              <summary className="text-xs text-muted-foreground cursor-pointer hover:text-foreground">
                View {r.dataSources.length} source URLs
              </summary>
              <ul className="mt-1 space-y-0.5">
                {r.dataSources.map((url: string, i: number) => (
                  <li key={i}>
                    <a href={url} target="_blank" rel="noopener noreferrer" className="text-xs text-primary hover:underline truncate block max-w-md">
                      [{i + 1}] {url}
                    </a>
                  </li>
                ))}
              </ul>
            </details>
          )}
          <p className="text-xs text-muted-foreground mt-2 italic">Gold Rush provides market signals and competitive intelligence. It does not predict success.</p>
        </div>

        {/* Key Stats */}
        <KeyStatsBar stats={r.keyStats || [
          { value: `${r.overallScore}/100`, label: "Market Signal Score", sentiment: r.overallScore >= 70 ? "positive" : r.overallScore >= 40 ? "neutral" : "negative" as any },
          { value: `${totalEvidence}+`, label: "Data Points Analyzed", sentiment: "neutral" as any },
          { value: safeValue(r.signalCards.find(c => c.title === "Trend Momentum")?.metrics?.[0]?.value), label: "Interest Change (90d)", change: r.signalCards.find(c => c.title === "Trend Momentum")?.metrics?.[0]?.value, sentiment: "positive" as any },
          { value: safeValue(r.revenueBenchmark.range), label: "Revenue Potential (est.)", sentiment: "positive" as any },
        ]} />

        {/* Founder Insight — moved to top (verdict layer) */}
        {r.founderInsight && <FounderInsight data={r.founderInsight} />}

        {/* Founder Decision — moved to top (verdict layer) */}
        {r.founderDecision && <FounderDecision data={r.founderDecision} />}

        {/* Data Quality & Integrity — collapsed group */}
        <DataQualityGroup report={r} userId={user?.id} analysisId={id} />


        {/* ═══════════════════════════════════════════════════════
            LAYER 2 — EXPLANATION
            ═══════════════════════════════════════════════════════ */}
        <ReportLayerHeader
          id="layer-explanation"
          title="Explanation"
          subtitle="Why this score happened"
          icon={<Brain className="w-4 h-4 text-teal" />}
        />

        {/* Score Deep Dive */}
        <CollapsibleSection title="Score Deep Dive" icon={<Brain className="w-4 h-4 text-teal" />} summary="Why you got this score">
          <ScoreDeepDive report={r} />
        </CollapsibleSection>

        {/* Signal Cards Grid */}
        <CollapsibleSection title="Signal Cards" icon={<Search className="w-4 h-4 text-primary" />} summary={`${r.signalCards.length} market signals analyzed`}>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {r.signalCards.map((card) => (
              <SignalCard key={card.title} card={card} subtitle={sectionSubtitles[card.title]} />
            ))}
          </div>
        </CollapsibleSection>

        {/* Opportunity */}
        <CollapsibleSection title="Opportunity Gaps" icon={<Target className="w-4 h-4 text-success" />} summary="Where you can win">
          <OpportunitySection opportunity={r.opportunity} />
        </CollapsibleSection>


        {/* ═══════════════════════════════════════════════════════
            LAYER 3 — EVIDENCE
            ═══════════════════════════════════════════════════════ */}
        <ReportLayerHeader
          id="layer-evidence"
          title="Evidence"
          subtitle="Supporting proof and raw signals"
          icon={<Search className="w-4 h-4 text-success" />}
        />

        {/* Proof Dashboard */}
        {r.proofDashboard && (
          <CollapsibleSection title="Proof Dashboard" icon={<Search className="w-4 h-4 text-success" />} summary="Verified evidence overview">
            <ProofDashboard data={r.proofDashboard} />
          </CollapsibleSection>
        )}

        {/* Evidence Strength */}
        <CollapsibleSection title="Evidence Strength" icon={<BarChart3 className="w-4 h-4 text-primary" />} summary="How strong is the proof?">
          <EvidenceStrength proofDashboard={r.proofDashboard} />
        </CollapsibleSection>

        {/* Keyword Demand */}
        {r.keywordDemand && (
          <CollapsibleSection title="Keyword Demand" icon={<Search className="w-4 h-4 text-teal" />} summary="Search volume insights">
            <KeywordDemand data={r.keywordDemand} />
          </CollapsibleSection>
        )}

        {/* User Quotes */}
        <CollapsibleSection title="User Quotes" icon={<MessageSquare className="w-4 h-4 text-purple-400" />} summary="What real users are saying">
          <UserQuotesSection quotes={(() => {
            if (r.userQuotes && r.userQuotes.length > 0) return r.userQuotes.slice(0, 5);
            const extracted = r.signalCards.flatMap(c =>
              c.evidence.map(e => {
                const match = e.match(/"([^"]+)"\s*—\s*(.+)/);
                if (!match) return null;
                const src = match[2];
                return {
                  text: match[1],
                  source: src,
                  platform: (src.toLowerCase().includes("reddit") || src.toLowerCase().includes("r/") ? "reddit" : src.toLowerCase().includes("app store") ? "app_store" : "other") as any,
                };
              }).filter(Boolean)
            ) as any[];
            return extracted.slice(0, 5);
          })()} />
        </CollapsibleSection>

        {/* App Store Intelligence */}
        {r.appStoreIntelligence && (
          <CollapsibleSection title="App Store Intelligence" icon={<Eye className="w-4 h-4 text-primary" />} summary="App store insights">
            <AppStoreIntelligence data={r.appStoreIntelligence} />
          </CollapsibleSection>
        )}

        {/* Open Source Landscape */}
        {r.githubRepos && (
          <CollapsibleSection title="Open Source Landscape" icon={<GitCompare className="w-4 h-4 text-muted-foreground" />} summary="Related open-source projects">
            <OpenSourceLandscape repos={r.githubRepos} />
          </CollapsibleSection>
        )}


        {/* ═══════════════════════════════════════════════════════
            LAYER 4 — DEEP ANALYSIS
            ═══════════════════════════════════════════════════════ */}
        <ReportLayerHeader
          id="layer-deep-analysis"
          title="Deep Analysis"
          subtitle="Advanced diagnostics and market intelligence"
          icon={<Microscope className="w-4 h-4 text-[hsl(262,60%,60%)]" />}
        />

        {/* Kill Shot Analysis */}
        {r.killShotAnalysis && (
          <CollapsibleSection title="Kill Shot Analysis" icon={<Crosshair className="w-4 h-4 text-destructive" />} summary="Critical risks and deal-breakers">
            <KillShotAnalysis data={r.killShotAnalysis} />
          </CollapsibleSection>
        )}

        {/* Market Exploit Map */}
        {r.marketExploitMap && (
          <CollapsibleSection title="Market Exploit Map" icon={<Map className="w-4 h-4 text-teal" />} summary="Gaps you can exploit">
            <MarketExploitMap data={r.marketExploitMap} />
          </CollapsibleSection>
        )}

        {/* Competitor Comparison Matrix */}
        {r.competitorMatrix && (
          <CollapsibleSection title="Competitor Matrix" icon={<GitCompare className="w-4 h-4 text-blue-400" />} summary="How you stack up">
            <CompetitorMatrix data={r.competitorMatrix} />
          </CollapsibleSection>
        )}

        {/* Review Intelligence */}
        {r.reviewIntelligence && r.reviewIntelligence.complaintClusters?.length > 0 && (
          <CollapsibleSection title="Review Intelligence" icon={<MessageSquare className="w-4 h-4 text-purple-400" />} summary="Competitor pain points">
            <ReviewIntelligence data={r.reviewIntelligence} />
          </CollapsibleSection>
        )}

        {/* Niche Deep Dive */}
        {r.nicheAnalysis && (
          <CollapsibleSection title="Niche Analysis" icon={<Target className="w-4 h-4 text-green-400" />} summary="Market positioning">
            <NicheAnalysis data={r.nicheAnalysis} />
          </CollapsibleSection>
        )}

        {/* Unit Economics */}
        {r.unitEconomics && (
          <CollapsibleSection title="Unit Economics" icon={<DollarSign className="w-4 h-4 text-primary" />} summary="Cost & revenue model">
            <UnitEconomics data={r.unitEconomics} />
          </CollapsibleSection>
        )}

        {/* Revenue Benchmark */}
        <CollapsibleSection title="Revenue Benchmark" icon={<BarChart3 className="w-4 h-4 text-green-500" />} summary={r.revenueBenchmark?.range || "Revenue estimates"}>
          <RevenueBenchmark benchmark={r.revenueBenchmark} />
        </CollapsibleSection>

        {/* Build Complexity */}
        {r.buildComplexity && (
          <CollapsibleSection title="Build Complexity" icon={<Wrench className="w-4 h-4 text-muted-foreground" />} summary={`${r.buildComplexity.complexityScore || "?"}/10 difficulty`}>
            <BuildComplexity data={r.buildComplexity} />
          </CollapsibleSection>
        )}

        {/* Recommended Strategy */}
        {r.recommendedStrategy && (
          <CollapsibleSection title="Recommended Strategy" icon={<Compass className="w-4 h-4 text-primary" />} summary="Suggested go-to-market approach" defaultOpen>
            <RecommendedStrategy data={r.recommendedStrategy} />
          </CollapsibleSection>
        )}

        {/* Glossary — collapsed by default */}
        <details className="mb-6">
          <summary className="text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground py-2">
            📖 Glossary of Terms
          </summary>
          <div className="mt-2">
            <GlossarySection />
          </div>
        </details>

        {/* Methodology — collapsed by default */}
        <details className="mb-6">
          <summary className="text-sm font-medium text-muted-foreground cursor-pointer hover:text-foreground py-2">
            🔬 Methodology
          </summary>
          <div className="mt-2">
            <MethodologySection methodology={r.methodology} dataSources={r.dataSources} />
          </div>
        </details>

        {/* Download & Track CTAs */}
        <div className="flex flex-col sm:flex-row gap-3 mt-10 mb-12 justify-center">
          <Button variant="default" size="lg" disabled={pdfGenerating} onClick={async () => {
            setPdfGenerating(true);
            try {
              toast.info("Generating PDF...");
              await new Promise(resolve => setTimeout(resolve, 50));
              generateReportPdf(r);
              toast.success("PDF downloaded!");
            } catch (err) {
              console.error("Report PDF generation failed:", err);
              toast.error("PDF generation failed. Please try again or use a desktop browser.");
            } finally {
              setPdfGenerating(false);
            }
          }}>
            {pdfGenerating ? (
              <><Loader2 className="mr-1 w-4 h-4 animate-spin" /> Generating…</>
            ) : (
              <><Download className="mr-1" /> Download Report PDF</>
            )}
          </Button>
          <Button
            variant={isTracked ? "secondary" : "outline"}
            size="lg"
            onClick={handleTrack}
            disabled={trackingLoading}
          >
            {isTracked ? <><BookmarkCheck className="mr-1" /> Tracking This Idea</> : <><Bookmark className="mr-1" /> Track This Idea</>}
          </Button>
          <Button variant="outline" size="lg" onClick={() => navigate("/dashboard")}>
            Analyze Another Idea <ArrowRight className="ml-1" />
          </Button>
        </div>

        {/* Blueprint Generator — below the report */}
        <BlueprintSection
          blueprint={r.blueprint}
          analysisId={id}
          idea={r.idea}
          pdfContext={{
            overallScore: r.overallScore,
            signalStrength: r.signalStrength,
            googleTrendsSparkline: r.signalCards.find(c => c.googleTrendsSparkline)?.googleTrendsSparkline,
            sparkline: r.signalCards.find(c => c.sparkline)?.sparkline,
            donut: r.signalCards.find(c => c.donut)?.donut,
            scoreBreakdown: r.scoreBreakdown,
          }}
          buildComplexity={r.buildComplexity}
          report={r}
        />
      </main>

      <footer className="text-center py-8 text-sm text-muted-foreground border-t border-border/50">
        © 2026 Gold Rush
      </footer>
    </div>
  );
};

export default Report;
